### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gopnikada** [antonyhell/report-telegram-channels#1]
node:fs:1334
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, mkdir 'D:\Proj\report-telegram-channels\dist\C:\Users\836D~1\AppData\Local\Temp\telegram_session'
    at Object.mkdirSync (node:fs:1334:3)
    at Object.mkdirSync (pkg/prelude/bootstrap.js:1508:33)
    at LocalStorage._init (C:\snapshot\telegram-report\node_modules\node-localstorage\LocalStorage.js:183:14)
    at new LocalStorage (C:\snapshot\telegram-report\node_modules\node-localstorage\LocalStorage.js:124:12)
    at new StoreSession (C:\snapshot\telegram-report\node_modules\telegram\sessions\StoreSession.js:15:54)
    at Object.getClient (C:\snapshot\telegram-report\src\telegram_utils.js)
    at run (C:\snapshot\telegram-report\src\index.js) {
  errno: -4058,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: 'D:\\Proj\\report-telegram-channels\\dist\\C:\\Users\\836D~1\\AppData\\Local\\Temp\\telegram_session'
}

**Comment by refactorraccoon** [comment]
fixed in latest version
